### PR TITLE
primary prayer implementation

### PR DESCRIPTION
**Pull request by ChavanShweta**
Fixes issue #396
extracting the primary payer information

### CODE REVIEW

**Comment by writetoritu** [comment]
- [ ] please add some comments to the code 
- [ ] set primary_payer_flag as boolean so 1 becomes TRUE and 2 becomes FALSE  and change the subsequent logic 

case when primary_payer_flag IS TRUE then plan_class||'-'||plan_type 
	     else 'NI' end as raw_payer_type_primary, 
	case when primary_payer_flag IS FALSE then plan_class||'-'||plan_type 
	     else 'NI' end as raw_payer_type_secondary, 
	case when primary_payer_flag IS TRUE then plan_name 
	     else 'NI' end as raw_payer_name_primary, 
	case when primary_payer_flag IS FALSE then plan_name 
	     else 'NI' end as raw_payer_name_secondary,
	case when primary_payer_flag IS TRUE then visit_payer_id 
	     else NULL end as raw_payer_id_primary,
	case when primary_payer_flag IS FALSE then visit_payer_id 
	     else NULL end as raw_payer_id_secondary,
	case when primary_payer_flag IS TRUE then payer 
	     else 'NI' end as payer_type_primary,
	case when primary_payer_flag IS FALSE then payer 
	     else 'NI' end as payer_type_secondary,

**Comment by ChavanShweta** [comment]
Have added the above mentioned in the code please review

**Comment by writetoritu** [comment]
thanks @ChavanShweta one more suggestion for change:  
Race 'NI' with NULL for payer_id columns as its an integer
```
case when primary_payer_flag is true then visit_payer_id
	     else NULL end as raw_payer_id_primary,
	case when primary_payer_flag is false then visit_payer_id
	     else NULL end as raw_payer_id_secondary,
```

**Comment by ChavanShweta** [comment]
Following replace NI with null for the payer

**Comment by writetoritu** [comment]
@ChavanShweta 'NI' was to be replaced by NULL `only` for the visit_payer_id related fields. 

Please see this
case when primary_payer_flag IS TRUE then plan_class||'-'||plan_type
else 'NI' end as raw_payer_type_primary,
case when primary_payer_flag IS FALSE then plan_class||'-'||plan_type
else 'NI' end as raw_payer_type_secondary,
case when primary_payer_flag IS TRUE then plan_name
else 'NI' end as raw_payer_name_primary,
case when primary_payer_flag IS FALSE then plan_name
else 'NI' end as raw_payer_name_secondary,
case when primary_payer_flag IS TRUE then visit_payer_id
else NULL end as raw_payer_id_primary,
case when primary_payer_flag IS FALSE then visit_payer_id
else NULL end as raw_payer_id_secondary,
case when primary_payer_flag IS TRUE then payer
else 'NI' end as payer_type_primary,
case when primary_payer_flag IS FALSE then payer
else 'NI' end as payer_type_secondary,

**Pull request merged**
