### PR TITLE
Updates to PEDSnet-PCORnet queries

### PR DESCRIPTION
**Pull request by toanong**
These issues were resolved
- Issue 72 - Revised Lab_result_CM query to incorporate new conventions
- Issue 73.- Truncated range_low and range_high to 10
- Issue 74.- Changed vital id to a sequential number

@burrowse Please review and merge.

### CODE REVIEW

**Comment by writetoritu** [comment]
Test results
- success on death_cause and Vital queries
- failed on lab_result_cm query for CHOP, Nemours and Nationwide (please see line notes)
- also minor update needed in lab_result query 
- the mappings need to be updated in txt version also

**Comment by toanong** [comment]
The problem missing data in measurement_result_date must be brought back to site. @writetoritu Do you agree with moving back to using measurement_date to populate result_date as a temporary fix?

**Comment by writetoritu** [comment]
result_date is an optional field in PEDSnet CDM and hence it's not a data quality issue with sites' data. 
How about we populate with measurement_date only if result_date is not available in source sites?

**Comment by toanong** [comment]
If it's required in PCORnet, can we make result_date a required field in PEDSnet for the next ETL cycle?

I like your suggestion however not sure how to make the distinction between the two dates in the PCORnet CDM. Would you please do a quick query to see how often result_date is different from measurement_date?

**Comment by gmschulte** [comment]
CHCOs understanding is the result_date and time is only for LABs, all other domains in this table (ht,wt,bp) are populated with the same value as measurement_date and time.

**Comment by writetoritu** [comment]
Interesting!
thanks @gmschulte for your input. 
discussion opened here: https://github.com/PEDSnet/Data_Models/issues/238

**Comment by writetoritu** [comment]
all changes are OK , except the logic for result_date which is being discussed in #77

**Pull request merged**
